SELECT problem_id problemId,
  problem_code problemCode,
  problem_name problemName,
  description,
  type_id typeId,
  sub_category_id subCategoryId,
  notes notes,
  priority_id priorityId,
  impact_id impactId,
  urgency_id urgencyId,
  problem_state problemState,
  access_id accessId,
  affected_node affectedNode,
  vendor,
  affected_service affectedService,
  location,
  location_id locationId,
  TO_CHAR(created_time, 'dd/mm/yyyy HH24:mi:ss') createdTime,
  TO_CHAR(last_update_time, 'dd/mm/yyyy HH24:mi:ss') lastUpdateTime,
  TO_CHAR(assign_time_temp, 'dd/mm/yyyy HH24:mi:ss') assignTimeTemp,
  TO_CHAR(es_rca_time, 'dd/mm/yyyy HH24:mi:ss') esRcaTime,
  TO_CHAR(es_wa_time, 'dd/mm/yyyy HH24:mi:ss') esWaTime,
  TO_CHAR(es_sl_time, 'dd/mm/yyyy HH24:mi:ss') esSlTime,
  TO_CHAR(started_time, 'dd/mm/yyyy HH24:mi:ss') startedTime,
  TO_CHAR(ended_time, 'dd/mm/yyyy HH24:mi:ss') endedTime,
  create_user_id createUserId,
  create_unit_id createUnitId,
  create_user_name createUserName,
  create_unit_name createUnitName,
  create_user_phone createUserPhone,
  TO_CHAR(deferred_time, 'dd/mm/yyyy HH24:mi:ss') deferredTime,
  insert_source insertSource,
  is_send_message isSendMessage,
  related_tt relatedTt,
  related_pt relatedPt,
  related_kedb relatedKedb,
  pt_type ptType,
  TO_CHAR(rca_found_time, 'dd/mm/yyyy HH24:mi:ss') rcaFoundTime,
  TO_CHAR(wa_found_time, 'dd/mm/yyyy HH24:mi:ss') waFoundTime,
  TO_CHAR(sl_found_time, 'dd/mm/yyyy HH24:mi:ss') slFoundTime,
  TO_CHAR(closed_time, 'dd/mm/yyyy HH24:mi:ss') closedTime,
  rca,
  wa,
  solution,
  solution_type solutionType,
  receive_unit_id receiveUnitId,
  receive_user_id receiveUserId,
  time_used timeUsed,
  worklog,
  influence_scope influenceScope,
  delay_time delayTime,
  rca_type rcaType,
  categorization,
  state_code stateCode,
  pt_related_type ptRelatedType,
  contact_info contactInfo,
  pm_group pmGroup,
  close_code closeCode,
  process,
  TO_CHAR(assigned_time, 'dd/mm/yyyy HH24:mi:ss') assignedTime,
  pm_id pmId,
  pm_user_name pmUserName,
  SOFTWARE_VERSION softwareVersion,
  HARDWARE_VERSION hardwareVersion,
  pt_duplicate ptDuplicate,
  reason_overdue reasonOverdue,
  is_chat isChat
FROM one_tm.Problems
WHERE 1 = 1
