select
  a.problem_id problemId,
  a.problem_code problemCode,
  a.problem_name problemName,
  a.description description,
  a.type_id typeId,
  a.sub_category_id subCategoryId,
  a.notes notes,
  a.priority_id priorityId,
  a.impact_id impactId,
  a.urgency_id urgencyId,
  b.item_name problemState,
  a.access_id accessId,
  a.affected_node affectedNode,
  a.vendor vendor,
  a.affected_service affectedService,
  a.location location,
  a.location_id locationId,
  a.created_time + :offset * interval '1' hour  createdTime,
  a.last_update_time + :offset * interval '1' hour  lastUpdateTime,
  a.assign_time_temp + :offset * interval '1' hour  assignTimeTemp,
  a.es_rca_time + :offset * interval '1' hour  esRcaTime,
  a.es_wa_time  + :offset * interval '1' hour   esWaTime,
  a.es_sl_time + :offset * interval '1' hour  esSlTime,
  a.started_time + :offset * interval '1' hour  startedTime,
  a.ended_time + :offset * interval '1' hour  endedTime,
  a.create_user_id createUserId,
  a.create_unit_id createUnitId,
  a.create_user_name createUserName,
  a.create_unit_name createUnitName,
  a.create_user_phone createUserPhone,
  a.deferred_time deferredTime,
  a.insert_source insertSource,
  a.is_send_message isSendMessage,
  a.related_tt relatedTt,
  a.related_pt relatedPt,
  a.related_kedb relatedKedb,
  a.pt_type ptType,
  a.rca_found_time  + :offset * interval '1' hour rcaFoundTime,
  a.wa_found_time  + :offset * interval '1' hour waFoundTime,
  a.sl_found_time  + :offset * interval '1' hour slFoundTime,
  a.closed_time  + :offset * interval '1' hour closedTime,
  a.rca rca,
  a.wa wa,
  a.solution solution,
  a.solution_type solutionType,
  a.receive_unit_id receiveUnitId,
  a.receive_user_id receiveUserId,
  a.time_used timeUsed, a.worklog,
  a.influence_scope influenceScope,
  a.delay_time  + :offset * interval '1' hour delayTime,
  a.rca_type rcaType,
  a.categorization,
  a.state_code stateCode,
  a.pt_related_type ptRelatedType,
  a.contact_info contactInfo,
  a.pm_group pmGroup,
  a.close_code closeCode,
  a.process process,
  a.assigned_time + :offset * interval '1' hour  assignedTime,
  a.pm_id pmId,
  a.pm_user_name pmUserName,
  a.SOFTWARE_VERSION softwareVersion,
  a.HARDWARE_VERSION  hardwareVersion,
  a.pt_duplicate ptDuplicate,
  a.reason_overdue reasonOverdue
from
  t a inner join common_gnoc.cat_item b on a.problem_state = b.item_id
where
  total >= 1 and 1 = 1
