WITH list_language_exchange AS
  (SELECT LE.LEE_ID,
    LE.APPLIED_SYSTEM,
    LE.APPLIED_BUSSINESS,
    LE.BUSSINESS_ID,
    LE.BUSSINESS_CODE,
    LE.LEE_LOCALE,
    LE.LEE_VALUE
  FROM COMMON_GNOC.LANGUAGE_EXCHANGE LE
  JOIN
    (SELECT *
    FROM COMMON_GNOC.CAT_ITEM
    WHERE CATEGORY_ID = 263
    AND ITEM_CODE     = 'OPEN_PM'
    ) CAT1
  ON LE.APPLIED_SYSTEM = CAT1.ITEM_VALUE
  JOIN
    (SELECT *
    FROM COMMON_GNOC.CAT_ITEM
    WHERE CATEGORY_ID = 262
    AND ITEM_CODE     = 'OPEN_PM.CR_MANAGER_ROLE'
    ) CAT2
  ON LE.APPLIED_BUSSINESS = CAT2.ITEM_VALUE
  WHERE LE.LEE_LOCALE     = :p_leeLocale
  ),
  list_result AS
  (SELECT CMR.CMRE_ID,
    CMR.CMRE_CODE,
    CASE
      WHEN llx.LEE_VALUE IS NULL
      THEN CMR.CMRE_NAME
      ELSE llx.LEE_VALUE
    END CMRE_NAME,
    CMR.DESCRIPTION,
    CMR.IS_SCHEDULE_CR_EMERGENCY,
    CMR.IS_ACTIVE
  FROM OPEN_PM.CR_MANAGER_ROLE CMR
  LEFT JOIN list_language_exchange llx
  ON CMR.CMRE_ID = llx.BUSSINESS_ID
  )
SELECT r.CMRE_ID cmreId,
  r.CMRE_CODE cmreCode,
  r.CMRE_NAME cmreName,
  r.DESCRIPTION description,
  r.IS_SCHEDULE_CR_EMERGENCY isScheduleCrEmergency,
  r.IS_ACTIVE status
FROM list_result r
WHERE 1=1
