WITH list_language_exchange AS
  (SELECT LE.LEE_ID,
    LE.APPLIED_SYSTEM,
    LE.APPLIED_BUSSINESS,
    LE.BUSSINESS_ID,
    LE.BUSSINESS_CODE,
    LE.LEE_LOCALE,
    LE.LEE_VALUE
  FROM COMMON_GNOC.LANGUAGE_EXCHANGE LE
  WHERE LE.LEE_LOCALE     = :p_leeLocale
    AND LE.APPLIED_SYSTEM    = 2
    AND LE.APPLIED_BUSSINESS = 22
  ),
  lst_data AS
  (SELECT MM.MATERIAL_ID MATERIAL_ID ,
    CASE
      WHEN llx.LEE_VALUE IS NULL
      THEN MM.MATERIAL_NAME
      ELSE TO_CHAR(llx.LEE_VALUE)
    END MATERIAL_NAME_EN,
    MM.SERIAL SERIAL ,
    MM.UNIT_PRICE UNIT_PRICE ,
    MM.DATE_TIME DATE_TIME ,
    MM.DEVICE_TYPE DEVICE_TYPE ,
    MM.MARKET_CODE MARKET_CODE,
    MATERIAL_NAME
  FROM OPEN_PM.MR_MATERIAL MM
  LEFT JOIN list_language_exchange llx
  ON llx.BUSSINESS_ID = MM.MATERIAL_ID
  )
select
    MATERIAL_ID materialId ,
    MATERIAL_NAME materialName,
    SERIAL serial ,
    UNIT_PRICE unitPrice ,
    TO_CHAR(DATE_TIME,'MM/yyyy') DATETIME ,
    DEVICE_TYPE deviceType ,
    MARKET_CODE marketCode,
    MATERIAL_NAME_EN materialNameEN
from lst_data where 1=1
