SELECT DISTINCT T1.USER_NAME username,
  T1.ROLE_CODE roleCode,
  T2.ROLE_NAME roleName,
  T1.IS_LEADER isLeader
FROM OPEN_PM.SR_ROLE_USER T1
INNER JOIN OPEN_PM.SR_ROLE T2
ON T1.ROLE_CODE = T2.ROLE_CODE
WHERE 1         = 1
AND STATUS      ='A'
