SELECT DISTINCT DEVICE_TYPE deviceType
FROM MR_DEVICE
WHERE (ARRAY_CODE = :arrayCode
              OR :arrayCode    IS NULL)
  AND NETWORK_TYPE  = :networkType
  AND DEVICE_TYPE  IS NOT NULL
ORDER BY DEVICE_TYPE
