SELECT distinct ARRAY_CODE arrayCode, NETWORK_TYPE networkType, DEVICE_TYPE deviceType
FROM OPEN_PM.MR_DEVICE
  WHERE 1 = 1
  AND ARRAY_CODE IS NOT NULL
  AND DEVICE_TYPE  IS NOT NULL
  AND NETWORK_TYPE IS NOT NULL
ORDER BY ARRAY_CODE, NETWORK_TYPE, DEVICE_TYPE
