SELECT A.ID id,
B.FULLNAME fullName,
A.USER_ID userId,
B.USERNAME userName,
B.EMAIL email,
B.MOBILE mobile,
C.UNIT_NAME unitName,
A.TYPE_CFG cfgType,
A.CFG_ID cfgId
FROM COMMON_GNOC.CFG_SMS_USER_GOING_OVERDUE A, COMMON_GNOC.USERS B, COMMON_GNOC.UNIT C
WHERE A.USER_ID = B.USER_ID AND B.UNIT_ID = C.UNIT_ID AND A.CFG_ID = :cfgId


