SELECT A.CFG_ID cfgId,
A.CFG_NAME cfgName,
A.UNIT_ID unitId,
C.UNIT_NAME unitName,
A.LOCATION_ID locationId,
A.LOCATION_NAME locationName,
A.PRIORITY_ID priorityId,
A.PRIORITY_NAME priorityName,
A.LEVEL_ID levelId,
d.ITEM_NAME levelName,
a.TIME_PROCESS timeProcess
FROM COMMON_GNOC.CFG_SMS_GOING_OVERDUE A,
COMMON_GNOC.UNIT C,
(select  * from COMMON_GNOC.CAT_ITEM  where CATEGORY_ID in (select  CATEGORY_ID from COMMON_GNOC.CATEGORY where CATEGORY_CODE = 'SMS_GOING_OVERDUE_LEVEL')) d

