WITH lst_lang AS
  (SELECT
    CASE
      WHEN l.LEE_VALUE IS NULL
      THEN c.ITEM_NAME
      ELSE l.LEE_VALUE
    END LEE_VALUE,
    c.ITEM_CODE ITEM_CODE
  FROM COMMON_GNOC.CAT_ITEM c
  LEFT JOIN COMMON_GNOC.LANGUAGE_EXCHANGE l
  ON c.ITEM_ID         = l.BUSSINESS_ID
  AND APPLIED_BUSSINESS=3
  AND l.APPLIED_SYSTEM =1
  AND l.LEE_LOCALE     =:lee_Locale
  WHERE c.STATUS       = 1
  AND c.CATEGORY_ID    =
    (SELECT CATEGORY_ID
    FROM COMMON_GNOC.CATEGORY
    WHERE CATEGORY_CODE='MR_SUBCATEGORY'
    AND STATUS         = 1
    )
  ORDER BY position,
    NLSSORT(ITEM_NAME,'NLS_SORT=vietnamese' )
  )
SELECT MR.SCHEDULE_ID scheduleId,
  MR.MARKET_CODE marketCode,
  CL.LOCATION_NAME marketName,
  CL.LOCATION_NAME nationName,
  MR.REGION region,
  MR.ARRAY_CODE arrayCode,
  CASE
    WHEN ll.LEE_VALUE IS NULL
    THEN MR.ARRAY_CODE
    ELSE TO_CHAR(ll.LEE_VALUE)
  END arrayName,
  MR.DEVICE_TYPE deviceType,
  MR.DEVICE_NAME deviceName,
  MR.DEVICE_CODE deviceCode,
  MR.DEVICE_ID deviceId,
  MR.IP_NODE ipNode,
  MR.VENDOR vendor,
  MR.BD_TYPE bdType,
  MR.STATION_CODE stationCode,
  DEV.NODE_AFFECTED nodeAffected,
  dev.OBJECT_ID objectId,
  MR.GROUP_CODE groupCode,
  TO_CHAR(MR.NEXT_DATE,'dd/MM/yyyy') nextDateStr,
  TO_CHAR(MR.LAST_DATE,'dd/MM/yyyy') lastDateStr,
  MR.NEXT_DATE nextDate,
  MR.LAST_DATE lastDate,
  MR.MR_ID mrId,
  MRG.MR_CODE mrCode,
  MR.WO_ID woId,
  WO.WO_CODE woCode,
  WL.WLG_TEXT wlgText,
  har.DESCRIPTION_CR descriptionCr,
  unit.IMPLEMENT_UNIT implementUnitId,
  u1.UNIT_NAME implementUnitName,
  unit.CHECKING_UNIT checkingUnitId,
  u2.UNIT_NAME checkingUnitName,
  har.CYCLE cycle,
  har.CYCLE_TYPE cycleType,
  MR.NOTE note,
  dev.UD ud,
  dev.DB db,
  DEV.BO_UNIT boUnit,
  dev.APPROVE_STATUS approveStatus,
  har.PROCEDURE_NAME procedureName,
  MR.PROCEDURE_ID procedureId,
  TO_CHAR(MR.NEXT_DATE_MODIFY,'dd/MM/yyyy') nextDateModifyStr,
  MR.NEXT_DATE_MODIFY nextDateModify,
  dev.LEVEL_IMPORTANT levelImportant,
  mr.IP_SERVER ipServer,
  dev.MR_CONFIRM_HARD mrConfirmHard,
  CF.CD_ID_HARD cdIdHard,
  CF.WO_GROUP_NAME cdIdHardStr,
  HAR.WO_CONTENT woContent,
  MR.UPDATE_DATE updatedDate
FROM OPEN_PM.MR_SCHEDULE_IT_HARD mr
LEFT JOIN COMMON_GNOC.CAT_LOCATION cl
ON CL.LOCATION_ID = MR.MARKET_CODE
LEFT JOIN OPEN_PM.MR_CFG_CR_IMPL_UNIT unit
ON MR.MARKET_CODE  = unit.MARKET_CODE
AND MR.DEVICE_TYPE = UNIT.DEVICE_TYPE_ID
AND MR.REGION      = unit.REGION
LEFT JOIN COMMON_GNOC.UNIT u1
ON unit.IMPLEMENT_UNIT = u1.UNIT_ID
LEFT JOIN COMMON_GNOC.UNIT u2
ON unit.CHECKING_UNIT = u2.UNIT_ID
LEFT JOIN OPEN_PM.MR_CFG_PROCEDURE_IT_HARD har
ON MR.PROCEDURE_ID = har.PROCEDURE_ID
LEFT JOIN OPEN_PM.MR_SYN_IT_DEVICES dev
ON MR.MARKET_CODE  = dev.MARKET_CODE
AND MR.DEVICE_TYPE = dev.DEVICE_TYPE
AND MR.DEVICE_ID   = dev.OBJECT_ID
AND dev.MR_HARD    =1
LEFT JOIN lst_lang ll
ON ll.ITEM_CODE = MR.ARRAY_CODE
LEFT JOIN
  (SELECT RTRIM(XMLAGG(XMLELEMENT(E,WLG_TEXT,',').EXTRACT('//text()')
  ORDER BY WLG_TEXT).GetClobVal(),',') AS WLG_TEXT,
    WLG_OBJECT_ID
  FROM OPEN_PM.WORK_LOG
  WHERE WLG_OBJECT_TYPE = 2
  GROUP BY WLG_OBJECT_ID
  ) wl
ON MR.CR_ID = WL.WLG_OBJECT_ID
LEFT JOIN
  (SELECT m.MARKET_CODE,
    m.REGION,
    m.ARRAY_CODE,
    m.DEVICE_TYPE,
    M.STATION_CODE,
    m.CD_ID_HARD,
    w.WO_GROUP_NAME
  FROM MR_HARD_UNIT_CONFIG m
  LEFT JOIN WFM.wo_cd_group w
  ON m.CD_ID_HARD        = w.WO_GROUP_ID
  ) CF ON MR.MARKET_CODE = CF.MARKET_CODE
AND MR.REGION            = CF.REGION
AND MR.ARRAY_CODE        = CF.ARRAY_CODE
AND mr.DEVICE_TYPE       = CF.DEVICE_TYPE
AND MR.STATION_CODE      = CF.STATION_CODE
LEFT JOIN OPEN_PM.MR mrg
ON MR.MR_ID = mrg.MR_ID
LEFT JOIN WFM.WO wo
ON MR.WO_ID = WO.WO_ID
WHERE 1     =1
