SELECT T1.ROLE_ID roleId,
  T1.COUNTRY country,
  T1.ROLE_CODE roleCode,
  L.LOCATION_NAME countryName,
  CASE
  WHEN T2.LEE_LOCALE = :p_leeLocale
  THEN (
        CASE
        WHEN T2.LEE_VALUE IS NOT NULL
        THEN T2.LEE_VALUE
        ELSE CAST(T1.ROLE_NAME AS NVARCHAR2(2000))
        END
        )
  ELSE CAST(T1.ROLE_NAME AS NVARCHAR2(2000))
  END roleName,
  T1.CREATED_USER createdUser,
  T1.CREATED_TIME createdTime,
  T1.UPDATED_USER updatedUser,
  T1.UPDATED_TIME updatedTime
FROM OPEN_PM.SR_ROLE T1
LEFT JOIN COMMON_GNOC.CAT_LOCATION L
ON T1.COUNTRY = L.LOCATION_ID
LEFT JOIN COMMON_GNOC.LANGUAGE_EXCHANGE T2
ON T1.ROLE_ID            = T2.BUSSINESS_ID
AND T2.APPLIED_SYSTEM    = 2
AND T2.APPLIED_BUSSINESS = 24
WHERE 1=1
