SELECT T1.ID_FILE idFile,
  T1.WO_ID woId,
  T1.FILE_NAME fileName,
  CASE
    WHEN gf.PATH IS NULL
    THEN TO_CHAR(T1.FILE_PATH)
    ELSE TO_CHAR(gf.PATH)
  END filePath,
  T1.USER_UPDATE userUpdate,
  T1.CHECK_LIST_ID checklistId ,
  TO_CHAR(T1.CREATED_DATE,'dd/MM/yyyy HH24:mi:ss') createdDate
FROM OPEN_PM.MR_SCHEDULE_BTS_HIS_FILE T1
LEFT JOIN COMMON_GNOC.GNOC_FILE gf
ON gf.BUSINESS_ID    = T1.ID_FILE
AND gf.MAPPING_ID    = T1.ID_FILE
AND gf.BUSINESS_CODE = 'MR_SCHEDULE_BTS_HIS_FILE'
WHERE 1              = 1
