SELECT t1.WO_CODE woCode,
       t1.CHECKLIST_ID checkListId,
       t1.CONTENT content ,
       t1.DEVICE_TYPE deviceType,
       t1.SERIAL serial,
       t1.PHOTO_REQ photoReq,
       t1.MIN_PHOTO minPhoto,
       t1.MAX_PHOTO maxPhoto,
       t1.CYCLE cycle,
       t1.CAPTURE_GUIDE captureGuide,
       t1.TASK_STATUS taskStatus,
       t1.SCHEDULE_HIS_DETAIL_ID scheduleBtsHisDetailId,
       t1.TASK_APPROVE taskApprove,
       t1.APPROVE_USER approveUser,
       t1.APPROVE_DATE approveDate,
       t1.WO_CODE_ORIGINAL woCodeOriginal,
       t1.IMES_ERROR_CODE imesErrorCode,
       t1.IMES_MESSAGE imesMessage,
       t1.TASK_APPROVE_AREA taskApproveArea,
       t1.REASON reason,
       t1.REASON_AREA reasonArea,
       t1.APPROVE_DATE_AREA approveDateArea,
       t1.APPROVE_USER_AREA approveUserArea,
       t1.SCORE_CHECKLIST scoreChecklist,
       t1.IS_IMPORTAINT isImportaint,
       t1.VALUE_AI valueAI,
       t1.PHOTO_RATE photoRate
FROM OPEN_PM.MR_SCHEDULE_BTS_HIS_DETAIL t1
WHERE 1           =1
