SELECT
c.ID id,
c.CFG_SUPPORT_CASE_ID cfgSupportCaseID,
b.CASE_NAME caseName,
a.TEST_CASE_NAME testCaseName,
c.CFG_SUPPORT_CASE_TEST_ID testCaseId,
c.RESULT result,
c.FILE_NAME fileName,
c.DESCRIPTION description,
d.WO_CODE woCode,
c.UPDATE_TIME updateTime
FROM wfm.CFG_SUPPORT_CASE_TEST a,
wfm.CFG_SUPPORT_CASE b,
wfm.WO_SUPPORT c,
wfm.WO d WHERE a.CFG_SUPPORT_CASE_ID = b.ID AND c.CFG_SUPPORT_CASE_ID = a.CFG_SUPPORT_CASE_ID AND c.CFG_SUPPORT_CASE_TEST_ID = a.ID AND c.WO_ID = d.WO_ID AND d.WO_CODE =:woCode
