SELECT
LOCATION_ID itemId,
LOCATION_CODE itemCode,
LOCATION_NAME itemName,
--PRE_CODE_STATION itemValue,
CASE WHEN PRE_CODE_STATION IS NULL THEN LOCATION_CODE
   ELSE PRE_CODE_STATION END itemValue,
LEVEL
FROM common_gnoc.cat_location
WHERE STATUS = 1
