SELECT
GT.GNOC_TIMEZONE_ID gnocTimezoneId,
GT.TIMEZONE_CODE timezoneCode,
GT.TIMEZONE_NAME timezoneName,
GT.NATION_CODE nationCode,
GT.TIMEZONE_OFFSET timezoneOffset,
CASE WHEN US.USER_ID IS NOT NULL THEN 1 ELSE 0 END AS isActive
FROM COMMON_GNOC.GNOC_TIMEZONE GT
LEFT JOIN COMMON_GNOC.USERS US ON US.USER_TIME_ZONE = GT.GNOC_TIMEZONE_ID AND US.USERNAME = :p_username
ORDER BY GT.TIMEZONE_NAME
