SELECT
GL.GNOC_LANGUAGE_ID gnocLanguageId,
GL.LANGUAGE_KEY languageKey,
GL.LANGUAGE_NAME languageName,
GL.LANGUAGE_FLAG languageFlag,
CASE WHEN US.USER_ID IS NOT NULL THEN 1 ELSE 0 END AS isActive
FROM COMMON_GNOC.GNOC_LANGUAGE GL
LEFT JOIN COMMON_GNOC.USERS US ON US.USER_LANGUAGE = GL.GNOC_LANGUAGE_ID AND US.USERNAME = :p_username
ORDER BY GL.LANGUAGE_NAME
