WITH lst_data AS
  (SELECT T1.SERVICE_ID itemId ,
    T1.SERVICE_CODE itemCode,
    CASE
      WHEN T6.LEE_LOCALE = :locale
      THEN (
        CASE
          WHEN T6.LEE_VALUE IS NOT NULL
          THEN T6.LEE_VALUE
          ELSE CAST(T1.SERVICE_NAME AS NVARCHAR2(2000))
        END )
      ELSE CAST(T1.SERVICE_NAME AS NVARCHAR2(2000))
    END itemName,
    T1.SERVICE_GROUP serviceGroup
  FROM OPEN_PM.SR_CATALOG T1
  INNER JOIN OPEN_PM.SR_CONFIG T2
  ON T1.SERVICE_ARRAY = T2.CONFIG_CODE
  AND T2.CONFIG_GROUP = 'SERVICE_ARRAY'
  INNER JOIN OPEN_PM.SR_CONFIG T3
  ON T1.SERVICE_GROUP = T3.CONFIG_CODE
  AND T3.CONFIG_GROUP = 'SERVICE_GROUP'
  AND T3.PARENT_CODE  = T2.CONFIG_CODE
  LEFT JOIN COMMON_GNOC.LANGUAGE_EXCHANGE T6
  ON T1.SERVICE_ID         = T6.BUSSINESS_ID
  AND T6.APPLIED_SYSTEM    =2
  AND T6.APPLIED_BUSSINESS = 21
  WHERE 1                  =1
  ORDER BY T1.COUNTRY,
    T1.SERVICE_ARRAY,
    T1.SERVICE_GROUP,
    T1.SERVICE_CODE
  )
SELECT data.itemId,data.itemCode,data.itemName FROM lst_data data WHERE 1=1
