SELECT ke.KEDB_ID kedbId,
ke.KEDB_CODE kedbCode,
ke.KEDB_NAME kedbName,
ke.DESCRIPTION description,
ke.INFLUENCE_SCOPE influenceScope,
ke.CREATE_USER_ID createUserId,
ke.CREATE_USER_NAME createUserName,
ke.RECEIVE_USER_ID receiveUserId,
ke.PT_TT_RELATED ptTtRelated,
ke.TYPE_ID typeId,
ke.SUB_CATEGORY_ID subCategoryId,
ke.VENDOR vendor,
ke.SOFTWARE_VERSION softwareVersion,
ke.TT_WA ttWa,
ke.RCA rca,
ke.PT_WA ptWa,
ke.SOLUTION solution,
ke.WORKLOG worklog,
TO_CHAR(ke.CREATED_TIME,'dd/MM/yyyy HH24:MI:ss') createdTime,
ke.KEDB_STATE kedbState,
ke.NOTES notes,
ke.RECEIVE_USER_NAME receiveUserName,
ke.HARDWARE_VERSION hardwareVersion,
ke.COMPLETER completer,
ke.COMPLETE_TIME completedTime,
ke.NUM_LIKE numLike,
ke.NUM_VIEW numView,
ke.COMMENTS comments,
ke.USERS_LIKE usersLike,
ke.UNIT_CHECK_ID unitCheckId,
ke.UNIT_CHECK_NAME unitCheckName,
ke.PARENT_TYPE_ID parentTypeId
FROM ONE_TM.Kedb ke
WHERE 1         = 1
