WITH list_language_exchange AS
  (SELECT LE.LEE_ID,
    LE.APPLIED_SYSTEM,
    LE.APPLIED_BUSSINESS,
    LE.BUSSINESS_ID,
    LE.BUSSINESS_CODE,
    LE.LEE_LOCALE,
    LE.LEE_VALUE
  FROM COMMON_GNOC.LANGUAGE_EXCHANGE LE
  JOIN
    (SELECT *
    FROM COMMON_GNOC.CAT_ITEM
    WHERE CATEGORY_ID = 263
    AND ITEM_CODE     = 'OPEN_PM'
    ) CAT1
  ON LE.APPLIED_SYSTEM = CAT1.ITEM_VALUE
  JOIN
    (SELECT *
    FROM COMMON_GNOC.CAT_ITEM
    WHERE CATEGORY_ID = 262
    AND ITEM_CODE     = 'OPEN_PM.CR_PROCESS'
    ) CAT2
  ON LE.APPLIED_BUSSINESS = CAT2.ITEM_VALUE
  WHERE LE.LEE_LOCALE     = :p_leeLocale
  ),
  list_data AS
  (SELECT a.CAS_ID CAS_ID ,
    a.TYPE TYPE ,
    a.NATION_CODE NATION_CODE ,
    a.VENDOR_CODE VENDOR_CODE ,
    a.VENDOR_NAME VENDOR_NAME ,
    a.MODULE_CODE MODULE_CODE ,
    a.MODULE_NAME MODULE_NAME ,
    a.APPROVAL_STATUS APPROVAL_STATUS ,
    a.APPROVAL_USER_ID APPROVAL_USER_ID ,
    a.FAULT_SRC FAULT_SRC ,
    a.FAULT_ID FAULT_ID ,
    a.FAULT_NAME FAULT_NAME ,
    a.FAULT_GROUP_NAME FAULT_GROUP_NAME ,
    a.FAULT_LEVEL_CODE FAULT_LEVEL_CODE ,
    a.DEVICE_TYPE_CODE DEVICE_TYPE_CODE ,
    CASE
      WHEN llx.LEE_VALUE IS NULL
      THEN b.CR_PROCESS_NAME
      ELSE llx.LEE_VALUE
    END CR_PROCESS_NAME,
    a.CR_PROCESS_ID CR_PROCESS_ID,
    a.AUTO_LOAD AUTO_LOAD,
    a.CREATED_USER CREATED_USER,
    b.IMPACT_SEGMENT_ID IMPACT_SEGMENT_ID,
    b.DEVICE_TYPE_ID DEVICE_TYPE_ID,
    a.keyword keyword,
    a.NUMBER_OCCURENCES
  FROM CR_ALARM_SETTTING a
  LEFT JOIN CR_PROCESS b
  ON a.CR_PROCESS_ID = b.CR_PROCESS_ID
  LEFT JOIN list_language_exchange llx
  ON a.cr_process_id = llx.BUSSINESS_ID
  )
SELECT CAS_ID casId ,
  TYPE type ,
  NATION_CODE nationCode ,
  VENDOR_CODE vendorCode ,
  VENDOR_NAME vendorName ,
  MODULE_CODE moduleCode ,
  MODULE_NAME moduleName ,
  APPROVAL_STATUS approvalStatus ,
  APPROVAL_USER_ID approvalUserId ,
  FAULT_SRC faultSrc ,
  FAULT_ID faultId ,
  FAULT_NAME faultName ,
  FAULT_GROUP_NAME faultGroupName ,
  FAULT_LEVEL_CODE faultLevelCode ,
  DEVICE_TYPE_CODE deviceTypeCode ,
  CR_PROCESS_NAME crProcessName,
  CR_PROCESS_ID crProcessId,
  AUTO_LOAD autoLoad,
  CREATED_USER createdUser,
  IMPACT_SEGMENT_ID crDomain,
  DEVICE_TYPE_ID deviceType,
  keyword,
  NUMBER_OCCURENCES numberOccurences
FROM list_data
WHERE 1=1
