SELECT T1.WL_ID wlId
 ,T1.WL_TYPE_ID wlTypeId
 ,T1.WL_TEXT wlText
 ,T1.CREATED_USER createdUser
 ,T1.CREATED_TIME createdTime
 ,T1.SR_ID srId
 ,T3.UNIT_NAME unitName
 FROM OPEN_PM.SR_WORKLOG T1
 LEFT JOIN COMMON_GNOC.USERS T2
 ON T1.CREATED_USER = T2.USERNAME
 LEFT JOIN COMMON_GNOC.UNIT T3
 ON T2.UNIT_ID = T3.UNIT_ID
 WHERE 1=1
