SELECT username
FROM
  (SELECT * FROM COMMON_GNOC.USERS WHERE UNIT_ID = :unit
  ) b1
JOIN COMMON_GNOC.ROLE_USER b2
ON b1.user_id = b2.USER_ID
JOIN COMMON_GNOC.ROLES b3
ON b2.ROLE_ID    = b3.ROLE_ID
WHERE 1          =1
AND b1.USERNAME  = :loginUser
AND b3.ROLE_CODE = :roleCode
