SELECT DISTINCT S.EXECUTION_UNIT unitId ,
  TO_CHAR(U.unit_code
  || ' ('
  || U.unit_name
  || ')') unitName ,
  U.UNIT_CODE
FROM OPEN_PM.SR_CATALOG S
JOIN COMMON_GNOC.UNIT U
ON S.EXECUTION_UNIT = U.UNIT_ID
LEFT JOIN OPEN_PM.SR_ROLE_USER R
ON R.UNIT_ID = S.EXECUTION_UNIT
WHERE 1      =1
