WITH tmp_language AS
  (SELECT APPLIED_BUSSINESS,
    BUSSINESS_ID,
    LEE_VALUE,
    LEE_LOCALE
  FROM COMMON_GNOC.LANGUAGE_EXCHANGE
  WHERE APPLIED_SYSTEM = 2
  AND APPLIED_BUSSINESS BETWEEN 20 AND 21
  )
SELECT T1.sr_id srId,
  T1.sr_code srCode,
  T1.title title,
  T1.description description,
  tU.PATHNAME pathSrUnit ,
  T1.sr_user srUser,
  CASE
      WHEN leService.LEE_LOCALE = :locale
      THEN (
        CASE
          WHEN leService.LEE_VALUE IS NOT NULL
          THEN leService.LEE_VALUE
          ELSE CAST(T2.SERVICE_NAME AS NVARCHAR2(2000))
        END )
      ELSE CAST(T2.SERVICE_NAME AS NVARCHAR2(2000))
    END serviceName ,
  T3.CONFIG_NAME statusName
FROM SR T1
INNER JOIN OPEN_PM.SR_CATALOG T2
ON T1.SERVICE_ID = T2.SERVICE_ID
LEFT JOIN tmp_language leService
ON T2.SERVICE_ID                = leService.BUSSINESS_ID
AND leService.APPLIED_BUSSINESS = 21
LEFT JOIN COMMON_GNOC.V_UNIT_AS_TREE tU
  ON tU.UNIT_ID = t1.SR_UNIT
INNER JOIN OPEN_PM.SR_CONFIG T3
  ON T1.STATUS        = T3.CONFIG_CODE
  AND T3.CONFIG_GROUP = 'STATUS'
WHERE 1=1
