SELECT T1.SERVICE_ID serviceId ,
  T1.COUNTRY country,
  T1.SERVICE_ARRAY serviceArray ,
  T1.SERVICE_GROUP serviceGroup,
  T1.SERVICE_CODE serviceCode,
  CASE
    WHEN T6.LEE_LOCALE = :locale
    THEN (
      CASE
        WHEN T6.LEE_VALUE IS NOT NULL
        THEN T6.LEE_VALUE
        ELSE CAST(T1.SERVICE_NAME AS NVARCHAR2(2000))
      END )
    ELSE CAST(T1.SERVICE_NAME AS NVARCHAR2(2000))
  END serviceName ,
  CASE
    WHEN tArray.LEE_LOCALE = :locale
    THEN (
      CASE
        WHEN tArray.LEE_VALUE IS NOT NULL
        THEN tArray.LEE_VALUE
        ELSE CAST(T2.CONFIG_NAME AS NVARCHAR2(2000))
      END )
    ELSE CAST(T2.CONFIG_NAME AS NVARCHAR2(2000))
  END serviceArrayName ,
  CASE
    WHEN tGroup.LEE_LOCALE = :locale
    THEN (
      CASE
        WHEN tGroup.LEE_VALUE IS NOT NULL
        THEN tGroup.LEE_VALUE
        ELSE CAST(T3.CONFIG_NAME AS NVARCHAR2(2000))
      END )
    ELSE CAST(T3.CONFIG_NAME AS NVARCHAR2(2000))
  END serviceGroupName ,
  T1.EXECUTION_UNIT executionUnit,
  T5.UNIT_NAME executionUnitDesc ,
  T1.STATUS status,
  T1.SERVICE_DESCRIPTION serviceDescription,
  T1.REPLY_TIME replyTime ,
  T1.EXECUTION_TIME executionTime,
  T1.ATTACH_FILE attachFile ,
  T1.CR cr ,
  T1.WO wo ,
  T1.IS_INPUT_CHECKING isInputChecking,
  T1.IS_OUTPUT_CHECKING isOutputChecking,
  T1.APPROVE approve,
  T1.ROLE_CODE roleCode,
  T1.FLOW_EXECUTE flowExecute ,
  T4.FLOW_NAME flowExecuteName,
  T1.IS_ADD_DAY isAddDay,
  T1.RENEW_DAY renewDay,
  T1.CR_WO_CREATE_TIME createdTimeCRWO,
  T1.AUTO_GENERATION_CYCLES autoGenerationCycles
FROM OPEN_PM.SR_CATALOG T1
INNER JOIN OPEN_PM.SR_CONFIG T2
ON T1.SERVICE_ARRAY = T2.CONFIG_CODE
AND T2.CONFIG_GROUP = 'SERVICE_ARRAY'
INNER JOIN OPEN_PM.SR_CONFIG T3
ON T1.SERVICE_GROUP = T3.CONFIG_CODE
AND T3.CONFIG_GROUP = 'SERVICE_GROUP'
AND T3.PARENT_CODE  = T2.CONFIG_CODE
LEFT JOIN OPEN_PM.SR_FLOW_EXECUTE T4
ON T1.FLOW_EXECUTE = T4.FLOW_ID
LEFT JOIN COMMON_GNOC.UNIT T5
ON T1.EXECUTION_UNIT = T5.UNIT_ID
LEFT JOIN COMMON_GNOC.LANGUAGE_EXCHANGE T6
ON T1.SERVICE_ID         = T6.BUSSINESS_ID
AND T6.APPLIED_SYSTEM    =2
AND T6.APPLIED_BUSSINESS = 21
LEFT JOIN COMMON_GNOC.LANGUAGE_EXCHANGE tArray
ON T2.CONFIG_ID              = tArray.BUSSINESS_ID
AND tArray.APPLIED_SYSTEM    =2
AND tArray.APPLIED_BUSSINESS = 20
LEFT JOIN COMMON_GNOC.LANGUAGE_EXCHANGE tGroup
ON T3.CONFIG_ID              = tGroup.BUSSINESS_ID
AND tGroup.APPLIED_SYSTEM    =2
AND tGroup.APPLIED_BUSSINESS = 20
WHERE 1                      =1
