SELECT 
T1.SERVICE_ID serviceId 
,T1.COUNTRY country 
,T1.SERVICE_ARRAY serviceArray 
,T1.SERVICE_GROUP serviceGroup 
,T1.SERVICE_CODE serviceCode 
,T1.SERVICE_NAME serviceName 
,T1.EXECUTION_UNIT executionUnit 
,T1.STATUS status 
,T1.SERVICE_DESCRIPTION serviceDescription 
,T1.REPLY_TIME replyTime 
,T1.EXECUTION_TIME executionTime 
,T1.ATTACH_FILE attachFile 
,T1.CR cr 
,T1.WO wo 
,T1.IS_INPUT_CHECKING isInputChecking
,T1.IS_OUTPUT_CHECKING isOutputChecking
,t1.role_code roleCode
FROM OPEN_PM.SR_CATALOG T1 
INNER JOIN OPEN_PM.SR_CONFIG T2 
ON T1.SERVICE_ARRAY = T2.CONFIG_CODE AND T2.CONFIG_GROUP = 'SERVICE_ARRAY' 
INNER JOIN OPEN_PM.SR_CONFIG T3 
ON T1.SERVICE_GROUP = T3.CONFIG_CODE AND T3.CONFIG_GROUP = 'SERVICE_GROUP' AND T3.PARENT_CODE = T2.CONFIG_CODE 
WHERE 1=1
