SELECT
  A.ROLE_ACTION_ID roleActionId ,
  A.ROLE_TYPE roleType ,
  D3.CONFIG_NAME roleTypeName,
  A.CURRENT_STATUS currentStatus ,
  D1.CONFIG_NAME currentStatusName,
  A.NEXT_STATUS nextStatus ,
  A.ACTIONS actions ,
  A.CREATED_USER createdUser ,
  A.CREATED_TIME createdTime ,
  A.UPDATED_USER updatedUser ,
  A.UPDATED_TIME updatedTime ,
  B.COUNTRY country ,
  A.FLOW_ID flowId ,
  A.GROUP_ROLE groupRole
 FROM
  OPEN_PM.SR_ROLE_ACTIONS A
  LEFT JOIN OPEN_PM.SR_CONFIG D1
  ON A.CURRENT_STATUS = D1.CONFIG_CODE
  AND D1.CONFIG_GROUP = 'STATUS' AND D1.STATUS = 'A'
  LEFT JOIN OPEN_PM.SR_CONFIG D3
  ON A.ROLE_TYPE = D3.CONFIG_CODE
 INNER JOIN OPEN_PM.SR_FLOW_EXECUTE B
 ON A.FLOW_ID = B.FLOW_ID AND A.FLOW_ID IS NOT NULL
 WHERE 1 = 1
