SELECT
  CASE
    WHEN LE.LEE_VALUE IS NULL
    THEN to_char(cf.CONFIG_NAME)
    ELSE to_char(LE.LEE_VALUE)
  END actionsName,
  CONFIG_CODE actions ,
  CONFIG_ID roleActionId ,
  LE.BUSSINESS_ID,
  LE.LEE_VALUE
FROM OPEN_PM.SR_CONFIG cf
LEFT JOIN COMMON_GNOC.LANGUAGE_EXCHANGE LE
ON LE.BUSSINESS_ID       = cf.CONFIG_ID
AND LE.LEE_LOCALE        = :p_leeLocale
AND LE.APPLIED_SYSTEM    = 2
AND LE.APPLIED_BUSSINESS = 20
WHERE CONFIG_GROUP       = 'SR_ACTION'
AND PARENT_GROUP         = 'ROLE_ACTION_TYPE'
AND PARENT_CODE          = :roleType
AND STATUS               = 'A'
