SELECT
  CASE
    WHEN COUNT(*) > 1
    THEN MIN(GENERATE_NO)
    ELSE -1
  END timeOffset
FROM
  (SELECT NVL(b1.GENERATE_NO,0) GENERATE_NO
  FROM OPEN_PM.SR_CATALOG_CHILD b1
  JOIN OPEN_PM.SR_CATALOG b2
  ON b1.SERVICE_ID_CHILD    = b2.SERVICE_ID
  AND b1.SERVICE_CODE_CHILD = b2.SERVICE_CODE
  JOIN OPEN_PM.SR_CATALOG b3
  ON b1.SERVICE_ID = b3.SERVICE_ID
  WHERE b1.SERVICE_CODE =:serviceCode and b1.SERVICE_ID =:serviceId and b2.STATUS =:status and b1.AUTO_CREATE_SR = 1
  GROUP BY NVL(b1.GENERATE_NO,0)
  )
