SELECT b1.CHILD_ID childId ,
  b1.SERVICE_ID serviceId ,
  b1.SERVICE_CODE serviceCode,
  b1.SERVICE_ID_CHILD serviceIdChild ,
  b1.SERVICE_CODE_CHILD serviceCodeChild,
  b1.AUTO_CREATE_SR autoCreateSR,
  b2.SERVICE_NAME serviceNameChild,
  b2.EXECUTION_UNIT executionUnitChild,
  b3.EXECUTION_UNIT executionUnitParent,
  NVL(b1.GENERATE_NO,0) generateNo
FROM OPEN_PM.SR_CATALOG_CHILD b1
JOIN OPEN_PM.SR_CATALOG b2
ON b1.SERVICE_ID_CHILD    = b2.SERVICE_ID
AND b1.SERVICE_CODE_CHILD = b2.SERVICE_CODE
JOIN OPEN_PM.SR_CATALOG b3
ON b1.SERVICE_ID = b3.SERVICE_ID
WHERE 1          =1
