SELECT
a.ID id,
a.NETWORK_LEVEL_ID netWorkLevelID,
a.NETWORK_LEVEL_NAME netWorkLevelName,
a.TROUBLE_TYPE_NAME troubleTypeName,
a.TROUBLE_TYPE_ID troubleTypeID
FROM ONE_TM.CFG_MAP_NET_LEVEL_INC_TYPE a
WHERE a.ID =:ID;
