SELECT
  GF.PATH path,
  GF.FILE_NAME fileName
FROM COMMON_GNOC.GNOC_FILE GF
INNER JOIN COMMON_GNOC.USERS US ON US.USER_ID = GF.CREATE_USER_ID
WHERE GF.BUSINESS_CODE = 'TROUBLE_FILE' AND GF.BUSINESS_ID = :troubleId
