 SELECT
	a.trouble_id troubleId,
	 a.trouble_name troubleName,
	 a.trouble_code troubleCode,
	 a.type_id typeId,
	 a.description,
	 a.priority_id priorityId,
	 a.sub_category_id subCategoryId,
	 a.impact_id impactId,
	 a.state,
	 a.affected_node affectedNode,
	 a.affected_service affectedService,
	 a.location_id locationId,
	 a.location,
	 to_char(a.created_time,'dd/MM/yyyy HH24:MI:ss') createdTime,
	 to_char(a.last_update_time,'dd/MM/yyyy HH24:MI:ss') lastUpdateTime,
	 to_char(a.assign_time,'dd/MM/yyyy HH24:MI:ss') assignTime,
	 to_char(a.begin_trouble_time,'dd/MM/yyyy HH24:MI:ss') beginTroubleTime,
	 to_char(a.end_trouble_time,'dd/MM/yyyy HH24:MI:ss') endTroubleTime,
	 to_char(a.deferred_time,'dd/MM/yyyy HH24:MI:ss') deferredTime,
	 a.create_user_id createUserId,
	 a.deferred_reason deferredReason,
	 a.create_unit_id createUnitId,
	 a.create_user_name createUserName,
	 a.create_unit_name createUnitName,
	 a.insert_source insertSource,
	 a.related_pt relatedPt,
	 a.vendor_id vendorId,
	 a.related_kedb relatedKedb,
	 a.receive_unit_id receiveUnitId,
	 a.receive_user_id receiveUserId,
	 a.receive_unit_name receiveUnitName,
	 a.receive_user_name receiveUserName,
	 a.root_cause rootCause,
	 a.work_arround workArround,
	 a.solution_type solutionType,
	 a.work_log workLog,
	 a.rejected_code rejectedCode,
	 a.reject_reason rejectReason,
	 a.risk,
	 a.close_code closeCode,
	 a.support_unit_id supportUnitId,
	 a.support_unit_name supportUnitName,
	 to_char(a.queue_time,'dd/MM/yyyy HH24:MI:ss') queueTime,
	 to_char(a.clear_time,'dd/MM/yyyy HH24:MI:ss') clearTime,
	 to_char(a.closed_time,'dd/MM/yyyy HH24:MI:ss') closedTime,
	 a.reason_overdue reasonOverdue,
	 a.time_zone_create timeZoneCreate,
	 p.item_name priorityName,
	 s.item_name stateName,
	 mang.item_name typeName,
	 a.tbl_curr tblCurr,
	 a.tbl_his tblHis,
	 a.tbl_clear tblClear,
	 a.alarm_id alarmId,
	 a.reason_id reasonId,
	 a.reason_name reasonName,
	 case when a.reason_id is null then 0 else 1 end reasonExist
FROM
  one_tm.troubles a,
  common_gnoc.cat_item p,
  common_gnoc.cat_item s,
  common_gnoc.cat_item mang
WHERE
  a.priority_id = p.item_id
  AND a.state = s.item_id
  AND a.type_id = mang.item_id
  AND a.CREATED_TIME > sysdate - 60
