SELECT t1.TROUBLE_ID,
  t1.TROUBLE_NAME,
  t1.TROUBLE_CODE,
  t1.DESCRIPTION,
  t1.INFO_TICKET,
  t1.RECEIVE_USER_NAME,
  t1.ROOT_CAUSE,
  t1.REASON_ID,
  t1.SOLUTION_TYPE,
  t1.WORK_ARROUND,
  t1.REJECTED_CODE,
  CASE
    WHEN t1.STATE = 3
    OR t1.STATE   = 5
    OR t1.STATE   = 6
    OR t1.STATE   = 8
    OR t1.STATE   = 9
    OR t1.STATE   = 10
    OR t1.STATE   = 11
    THEN (NVL(t1.TIME_PROCESS,0) - (NVL(t1.TIME_USED,0)) + ROUND((NVL(t1.CLEAR_TIME, sysdate) - NVL(t1.ASSIGN_TIME_TEMP, t1.ASSIGN_TIME))*24,2))
    WHEN t1.STATE = 7
    THEN NVL(t1.TIME_PROCESS,0)- NVL(t1.TIME_USED,0)
    ELSE NULL
  END remainTime,
  CASE
    WHEN t1.STATE = 4
    THEN t1.REJECTED_CODE
    ELSE NULL
  END rejectedCode,
  CASE
    WHEN t1.STATE = 4
    THEN t1.REJECT_REASON
    ELSE NULL
  END rejectReason
FROM ONE_TM.TROUBLES t1
WHERE 1 =1
AND t1.STATE          <> 11
