SELECT   a.trouble_id troubleId,
                                        a.trouble_name troubleName,
                                        a.trouble_code troubleCode,
                                        a.description,
                                        a.type_id typeId,
                                        a.sub_category_id subCategoryId,
                                        a.priority_id priorityId,
                                        a.impact_id impactId,
                                        a.state,
                                        a.affected_node affectedNode,
                                        a.affected_service affectedService,
                                        a.location,
                                        a.location_id locationId,
                                        a.created_time createdTime,
                                        a.last_update_time lastUpdateTime,
                                        a.assign_time assignTime,
                                        a.assign_time_temp assignTimeTemp,
                                        a.begin_trouble_time beginTroubleTime,
                                        a.end_trouble_time endTroubleTime,
                                        a.deferred_time deferredTime,
                                        a.create_user_id createUserId,
                                        a.deferred_reason deferredReason,
                                        a.create_unit_id createUnitId,
                                        a.create_user_name createUserName,
                                        a.create_unit_name createUnitName,
                                        a.insert_source insertSource,
                                        a.related_pt relatedPt,
                                        a.vendor_id vendorId,
                                        a.related_kedb relatedKedb,
                                        a.receive_unit_id receiveUnitId,
                                        a.receive_user_id receiveUserId,
                                        a.receive_unit_name receiveUnitName,
                                        a.receive_user_name receiveUserName,
                                        a.root_cause rootCause,
                                        a.work_arround workArround,
                                        a.solution_type solutionType,
                                        a.work_log workLog,
                                        a.rejected_code rejectedCode,
                                        a.reject_reason rejectReason,
                                        a.risk,
                                        a.close_code closeCode,
                                        a.support_unit_id supportUnitId,
                                        a.support_unit_name supportUnitName,
                                        a.queue_time queueTime,
                                        a.clear_time clearTime,
                                        a.closed_time closedTime,
                                        a.reason_overdue reasonOverdue,
                                        a.time_zone_create timeZoneCreate,
                                        p.item_name priorityName, p.item_code priorityCode,
                                        s.item_name stateName,
                                        mang.item_name typeName,
                                        a.reason_id reasonId,
                                        a.reason_name reasonName,
                                        case when s.item_code in('WAITING RECEIVE','QUEUE','SOLUTION FOUND','CLEAR','CLOSED','CLOSED NOT KEDB','WAIT FOR DEFERRED')
                                             then nvl(a.time_used,0) + round( (nvl(a.clear_time,sysdate)-nvl(a.assign_time_temp,a.assign_time))*24 ,2)
                                             else nvl(a.time_used,0) end timeUsed,
                                        case when s.item_code in('WAITING RECEIVE','QUEUE','SOLUTION FOUND','CLEAR','CLOSED','CLOSED NOT KEDB','WAIT FOR DEFERRED')
                                             then nvl(a.time_process,0)- (nvl(a.time_used,0) + round( (nvl(a.clear_time,sysdate)-nvl(a.assign_time_temp,a.assign_time))*24,2))
                                             when s.item_code in ('DEFERRED')
                                             then nvl(a.time_process,0)- nvl(a.time_used,0)
                                             else null end remainTime,
                                        a.alarm_id alarmId,
                                        a.time_create_cfg timeCreateCfg,
                                        a.time_process timeProcess,
                                        a.tbl_curr tblCurr,
                                        a.tbl_his tblHis,
                                        a.tbl_clear tblClear,
                                        a.REASON_LV1_ID reasonLv1Id,
                                        a.REASON_LV1_NAME reasonLv1Name,
                                        a.REASON_LV2_ID reasonLv2Id,
                                        a.REASON_LV2_NAME reasonLv2Name,
                                        a.REASON_LV3_ID reasonLv3Id,
                                        a.REASON_LV3_NAME reasonLv3Name,
                                        a.REASON_OVERDUE_ID reasonOverdueId,
                                        a.REASON_OVERDUE_NAME reasonOverdueName,
                                        a.REASON_OVERDUE_ID_2 reasonOverdueId2,
                                        a.REASON_OVERDUE_NAME_2 reasonOverdueName2,
                                        a.SPM_CODE spmCode,
                    a.network_level networkLevel,
                    a.auto_Create_WO autoCreateWO,
                    a.line_Cut_Code lineCutCode,
                    a.code_Snippet_Off codeSnippetOff,
                    a.cable_Type cableType,
                    a.closures_Replace closuresReplace,
                    a.where_Wrong whereWrong,
                    a.asessment_Data asessmentData,
                    a.alarm_group alarmGroupId,
                    a.service_type serviceType,
                    a.complaint_group_id complaintGroupId,
                    a.close_tt_time closeTtTime,
                    a.trans_network_type_id transNetworkTypeId,
                    a.trans_reason_effective_id transReasonEffectiveId,
                    a.trans_reason_effective_content transReasonEffectiveContent,
                    a.auto_close autoClose,
                    a.wo_code woCode,
                    a.clear_user_id clearUserId,
                    a.clear_user_name clearUserName,
                    alarm.item_name alarmGroupName,
                    a.related_trouble_codes relatedTroubleCodes,
                    a.re_occur reOccur,
                    a.DATE_MOVE dateMove,
                    a.IS_MOVE isMove,
                    a.UNIT_MOVE unitMove,
                    a.UNIT_MOVE_NAME unitMoveName,
                    a.is_update_after_closed isUpdateAfterClosed,
                    a.reject_time rejectTime,
                    a.IS_STATION_VIP isStationVip, a.is_tick_help isTickHelp, a.num_pending numPending,
                    a.NUM_AON numAon, a.NUM_GPON numGpon, a.NUM_NEXTTV numNexttv, a.NUM_THC numThc, a.technology,
                    a.info_Ticket infoTicket, a.Catching_time catchingTime,
                    a.num_help numHelp, a.ami_id amiId, a.RELATED_CR relatedCr, a.NATION_CODE nationCode,
                    a.is_chat isChat, a.complaint_id complaintId, a.num_reassign numReassign,
                    a.DEFER_TYPE deferType, a.ESTIMATE_TIME estimateTime, a.LONGITUDE longitude,
                    a.LATITUDE latitude, a.GROUP_SOLUTION groupSolution, a.CELL_SERVICE cellService, a.CONCAVE concave,
                    a.error_code errorCode, a.is_send_tktu isSendTktu, a.trouble_assign_id troubleAssignId,
                    a.CREATE_UNIT_ID_BY_CC createUnitIdByCC, a.COMPLAINT_TYPE_ID complaintTypeId, a.COMPLAINT_PARENT_ID complaintParentId,
                    a.isdn, a.create_User_By_CC createUserByCC, a.lst_complaint lstComplaint, a.downtime,
                    a.TYPE_UNIT typeUnit, a.COUNT_REOPEN countReopen, a.NUM_AFFECT numAffect, a.SUB_MIN subMin,
                    a.warn_Level warnLevel, a.is_Fail_Device isFailDevice, a.country country, a.is_overdue isOverdue
                                 FROM   one_tm.troubles a, common_gnoc.cat_item p, common_gnoc.cat_item s,
                                common_gnoc.cat_item mang, common_gnoc.cat_item alarm
                                WHERE   a.priority_id = p.item_id
                                AND a.state = s.item_id
                                AND a.alarm_group = alarm.item_id
                                AND a.type_id = mang.item_id
