SELECT
    a.trouble_id troubleId,
    a.trouble_code troubleCode,
    a.trouble_name troubleName,
    a.description,
    a.type_id typeId,
    a.sub_category_id subCategoryId,
    a.priority_id priorityId,
    a.impact_id impactId,
    a.state,
    a.affected_node affectedNode,
    a.location,
    a.affected_service affectedService,
    a.location_id locationId,
    a.created_time createdTime,
    a.last_update_time lastUpdateTime,
    a.assign_time assignTime,
    a.begin_trouble_time beginTroubleTime,
    a.end_trouble_time endTroubleTime,
    a.deferred_time deferredTime,
    a.create_user_id createUserId,
    a.deferred_reason deferredReason,
    a.create_unit_id createUnitId,
    a.create_user_name createUserName,
    a.create_unit_name createUnitName,
    a.insert_source insertSource,
    a.related_pt relatedPt,
    a.vendor_id vendorId,
    a.related_kedb relatedKedb,
    a.receive_unit_id receiveUnitId,
    a.receive_user_id receiveUserId,
    a.receive_unit_name receiveUnitName,
    a.receive_user_name receiveUserName,
    a.root_cause rootCause,
    a.work_arround workArround,
    a.solution_type solutionType,
    rtrim(a.work_log,',') workLog,
    a.rejected_code rejectedCode,
    a.reject_reason rejectReason,
    a.risk,
    a.close_code closeCode,
    a.support_unit_id supportUnitId,
    a.support_unit_name supportUnitName,
    a.queue_time queueTime,
    a.clear_time clearTime,
    a.closed_time closedTime,
    a.reason_overdue reasonOverdue,
    a.time_zone_create timeZoneCreate,
    p.item_name priorityName,
    s.item_name stateName,
    mang.item_name typeName,
    a.reason_id reasonId,
    a.reason_name reasonName,
    case when s.item_code in('OPEN','WAITING RECEIVE','QUEUE','SOLUTION FOUND','CLEAR','CLOSED','CLOSED NOT KEDB') then nvl(a.time_used,0) + round( (nvl(a.clear_time,sysdate)-nvl(a.assign_time_temp,a.assign_time))*24 ,2) else nvl(a.time_used,0) end timeUsed,
    case when s.item_code in('OPEN','WAITING RECEIVE','QUEUE','SOLUTION FOUND','CLEAR','CLOSED','CLOSED NOT KEDB') then nvl(a.time_process,0)- (nvl(a.time_used,0) + round( (nvl(a.clear_time,sysdate)-nvl(a.assign_time_temp,a.assign_time))*24,2)) else null end remainTime,
    a.alarm_id alarmId,
    a.time_create_cfg timeCreateCfg,
    a.time_process timeProcess,
    a.tbl_curr tblCurr,
    a.tbl_his tblHis,
    a.tbl_clear tblClear
 FROM
    one_tm.troubles a, common_gnoc.cat_item p, common_gnoc.cat_item s,
    common_gnoc.cat_item mang
 WHERE
    a.priority_id = p.item_id
    AND a.state = s.item_id
    AND a.type_id = mang.item_id
