SELECT T1.HIS_ID hisId ,
  T1.CREATED_USER createdUser ,
  TO_CHAR(T1.CREATED_TIME,'dd/MM/yyyy HH24:mi:ss') createdTime ,
  T1.ACTION_CODE actionCode ,
  T1.COMMENTS comments ,
  T1.SR_ID srId ,
  T1.SR_STATUS srStatus ,
  T3.UNIT_NAME unitName
FROM OPEN_PM.SR_HIS T1
INNER JOIN COMMON_GNOC.USERS T2
ON T1.CREATED_USER = T2.USERNAME
INNER JOIN COMMON_GNOC.UNIT T3
ON T2.UNIT_ID = T3.UNIT_ID
WHERE 1       =1
