SELECT T1.SR_CODE srChildCode,
  CASE
    WHEN T1.SR_CODE =:srCode
    THEN :status
    ELSE T1.STATUS
  END status,
  T2.GENERATE_NO generateNo,
  T2.SR_PARENT_CODE srParentCode
FROM SR T1
INNER JOIN SR_CHILD_AUTO T2
ON T1.SR_CODE         =T2.SR_CHILD_CODE
AND T2.SR_PARENT_CODE = T1.PARENT_CODE
WHERE 1               =1
AND T2.GENERATE_NO    =
  (SELECT GENERATE_NO FROM SR_CHILD_AUTO WHERE SR_CHILD_CODE=:srCode
  )
AND T2.CREATE_SR      =1
AND T2.SR_PARENT_CODE =
  (SELECT PARENT_CODE FROM SR WHERE SR_CODE =:srCode
  )
