WITH list_language_exchange AS
  (SELECT LE.LEE_ID,
    LE.APPLIED_SYSTEM,
    LE.APPLIED_BUSSINESS,
    LE.BUSSINESS_ID,
    LE.BUSSINESS_CODE,
    LE.LEE_LOCALE,
    LE.LEE_VALUE
  FROM COMMON_GNOC.LANGUAGE_EXCHANGE LE
  JOIN
    (SELECT *
    FROM COMMON_GNOC.CAT_ITEM
    WHERE CATEGORY_ID = 263
    AND ITEM_CODE     = 'COMMON_GNOC'
    ) CAT1
  ON LE.APPLIED_SYSTEM = CAT1.ITEM_VALUE
  JOIN
    (SELECT *
    FROM COMMON_GNOC.CAT_ITEM
    WHERE CATEGORY_ID = 262
    AND ITEM_CODE     = 'COMMON_GNOC.CFG_CHILD_ARRAY'
    ) CAT2
  ON LE.APPLIED_BUSSINESS = CAT2.ITEM_VALUE
  WHERE LE.LEE_LOCALE     = :p_leeLocale
  ),
  list_result AS
  (SELECT ti.CHILDREN_ID,
    ti.PARENT_ID,
    CASE
      WHEN llx.LEE_VALUE IS NULL
      THEN ti.CHILDREN_CODE
      ELSE TO_CHAR(llx.LEE_VALUE)
    END CHILDREN_CODE,
    ti.STATUS,
    ti.UPDATED_USER,
    ti.UPDATED_TIME,
    CASE
      WHEN llx.LEE_VALUE IS NULL
      THEN ti.CHILDREN_NAME
      ELSE TO_CHAR(llx.LEE_VALUE)
    END CHILDREN_NAME
  FROM COMMON_GNOC.CFG_CHILD_ARRAY ti
  LEFT JOIN list_language_exchange llx
  ON ti.CHILDREN_ID = llx.BUSSINESS_ID
  )
SELECT t1.CHILDREN_ID childrenId,
  t1.PARENT_ID parentId,
  t1.STATUS status,
  t1.UPDATED_USER updatedUser,
  t1.UPDATED_TIME updatedTime,
  t1.CHILDREN_NAME childrenName,
  t1.CHILDREN_CODE childrenCode
FROM list_result t1
WHERE t1.STATUS = 1
