SELECT
t1.ID_IMPACT idImpact,
t1.EMP_ID empId,
t1.EMP_USERNAME empUsername,
t2.USERNAME userName,
t2.UNIT_ID unitId,
t1.EMP_ARRAY empArray ,
t1.EMP_LEVEL empLevel ,
t3.UNIT_NAME unitName,
t3.UNIT_CODE unitCode,
t1.UPDATED_USER updatedUser ,
t1.UPDATED_TIME updatedTime,
t1.EMP_ARRAY_CHILD empArrayChild,
ist.IMPACT_SEGMENT_NAME empArrayName,
t3.CHILDREN_NAME empArrayChildName
FROM COMMON_GNOC.EMPLOYEE_IMPACT
t1 INNER JOIN COMMON_GNOC.USERS t2 ON t1.EMP_ID = t2.USER_ID
LEFT JOIN COMMON_GNOC.UNIT t3 ON t2.UNIT_ID = t3.UNIT_ID
INNER JOIN OPEN_PM.IMPACT_SEGMENT ist ON ist.IS_ACTIVE = 1 AND ist.APPLIED_SYSTEM = 2 AND ist.IMPACT_SEGMENT_ID = t1.EMP_ARRAY
LEFT JOIN COMMON_GNOC.CFG_CHILD_ARRAY t3 ON  t1.EMP_ARRAY_CHILD = t3.CHILDREN_ID
WHERE 1 =1
