SELECT t.ID id,
  t.TT_CHANGE_STATUS_ID ttChangeStatusId,
  t.ROLE_ID roleId,
  ci.ITEM_NAME roleName
FROM ONE_TM.TT_CHANGE_STATUS_ROLE t
LEFT JOIN
  (SELECT *
  FROM COMMON_GNOC.CAT_ITEM
  WHERE STATUS        = 1
  AND PARENT_ITEM_ID IS NULL
  AND CATEGORY_ID     =
    (SELECT CATEGORY_ID
    FROM COMMON_GNOC.CATEGORY
    WHERE CATEGORY_CODE = :categoryCode
    AND status          = 1
    )
  ) ci
ON TO_CHAR(t.ROLE_ID)       = ci.ITEM_VALUE
WHERE t.TT_CHANGE_STATUS_ID = :ttChangeStatusId
ORDER BY t.ID ASC
