/*SELECT DISTINCT t2.RETURN_CATEGORY returnCategory,
  t1.ITEM_CODE returnCategoryName
FROM COMMON_GNOC.CAT_ITEM t1,
  OPEN_PM.RETURN_CODE_CATALOG t2
WHERE t1.CATEGORY_ID = 650
AND t1.ITEM_VALUE    = t2.RETURN_CATEGORY
ORDER BY t2.RETURN_CATEGORY ASC
*/
