WITH C2 as(
SELECT ITEM_ID, ITEM_NAME
FROM COMMON_GNOC.CAT_ITEM
WHERE STATUS        = 1
AND PARENT_ITEM_ID IS NULL
AND CATEGORY_ID     =
  (SELECT CATEGORY_ID
  FROM COMMON_GNOC.CATEGORY
  WHERE CATEGORY_CODE='GROUP_REASON_PT'
  )),
  C3 as(
SELECT ITEM_ID, ITEM_NAME
FROM COMMON_GNOC.CAT_ITEM
WHERE STATUS        = 1
AND PARENT_ITEM_ID IS NULL
AND CATEGORY_ID     =
  (SELECT CATEGORY_ID
  FROM COMMON_GNOC.CATEGORY
  WHERE CATEGORY_CODE='RADICAL_SOLUTION_PT'
  )),
    C4 as(
SELECT ITEM_ID, ITEM_NAME
FROM COMMON_GNOC.CAT_ITEM
WHERE STATUS        = 1
AND CATEGORY_ID     =
  (SELECT CATEGORY_ID
  FROM COMMON_GNOC.CATEGORY
  WHERE CATEGORY_CODE='PT_TYPE'
  )),
      C5 as(
SELECT ITEM_ID, ITEM_NAME
FROM COMMON_GNOC.CAT_ITEM
WHERE STATUS        = 1
AND CATEGORY_ID     =
  (SELECT CATEGORY_ID
  FROM COMMON_GNOC.CATEGORY
  WHERE CATEGORY_CODE='PT_SUB_CATEGORY'
  ))
SELECT C1.ID id,
  C1.REASON_GROUP_ID reasonGroupId,
  C2.ITEM_NAME reasonGroupName ,
  C1.SOLUTION_TYPE_ID solutionTypeId,
  C3.ITEM_NAME solutionTypeName,
  C1.TIME_PROCESS timeProcess,
  C1.CREATE_DATE createDate,
  C1.TYPE_ID typeId,
  C4.ITEM_NAME typeIdStr,
  C1.SUB_CATEGORY_ID subCategoryId,
  C5.ITEM_NAME subCategoryIdStr
FROM one_tm.CFG_TIME_PROBLEM_PROCESS C1
LEFT JOIN C2
ON C2.ITEM_ID = C1.REASON_GROUP_ID
LEFT JOIN C3
ON C3.ITEM_ID = C1.SOLUTION_TYPE_ID
LEFT JOIN C4
ON C4.ITEM_ID = C1.TYPE_ID
LEFT JOIN C5
ON C5.ITEM_ID = C1.SUB_CATEGORY_ID
WHERE 1 = 1

