SELECT T1.CR_ID crId ,
       T2.IS_PRIMARY_CR isPrimaryCr ,
       T2.RELATE_TO_PRIMARY_CR relateToPrimaryCr
FROM CR_CREATED_FROM_OTHER_SYS T1
       INNER JOIN CR T2
         ON T1.CR_ID        = T2.CR_ID
WHERE T1.SYSTEM_ID = 1
  AND T1.OBJECT_ID   = :objectId
  AND T1.CR_ID NOT  IN
      (SELECT CR_ID FROM MR_CR_RECREATED WHERE MR_ID = :mrId
      )
ORDER BY T2.IS_PRIMARY_CR
