SELECT
CP.PROCEDURE_ID procedureId,
CP.ARRAY_CODE arrayCode,
CA.ARRAY_NAME arrayCodeName,
CP.MARKET_CODE marketCode,
CP.DEVICE_TYPE deviceType,
CP.MR_CONTENT_ID mrContentId,
CP.PROCEDURE_NAME procedureName,
CP.CYCLE cycle,
CP.GEN_MR_BEFORE genMrBefore,
CP.MR_TIME mrTime,
CP.ARRAY_ACTION_NAME arrayActionName,
CP.WO_CONTENT woContent,
CP.PRIORITY_CODE priorityCode,
CP.IMPACT impact,
CP.MR_WORKS mrWorks,
cl.LOCATION_NAME marketName
FROM MR_CFG_PROCEDURE_CD CP
LEFT JOIN MR_CAT_ARRAY CA ON CA.ARRAY_CODE=CP.ARRAY_CODE
LEFT JOIN COMMON_GNOC.CAT_LOCATION cl ON (CP.MARKET_CODE  = cl.LOCATION_ID and cl.PARENT_ID is null and cl.status = 1)
WHERE 1 = 1
