SELECT T1.FLOW_ID flowId,
  T1.FLOW_NAME flowName,
  T1.FLOW_DESCRIPTION flowDescription,
  T1.COUNTRY country,
  L.LOCATION_NAME countryName,
  COUNT(T2.CURRENT_STATUS) stepNumber
FROM OPEN_PM.SR_FLOW_EXECUTE T1
LEFT JOIN OPEN_PM.SR_ROLE_ACTIONS T2
ON T1.FLOW_ID = T2.FLOW_ID
LEFT JOIN COMMON_GNOC.CAT_LOCATION L
ON T1.COUNTRY = L.LOCATION_ID
WHERE 1       = 1
