SELECT DISTINCT
t2.WLAY_TYPE wlayType,
t1.UGCY_NAME wlayNameType
FROM OPEN_PM.USER_GROUP_CATEGORY t1
LEFT JOIN OPEN_PM.WORK_LOG_CATEGORY t2
ON t1.UGCY_ID         = t2.WLAY_TYPE
AND t1.UGCY_IS_ACTIVE = 1
ORDER BY t2.WLAY_TYPE ASC
