WITH list_language_exchange AS
  (SELECT LE.LEE_ID,
    LE.APPLIED_SYSTEM,
    LE.APPLIED_BUSSINESS,
    LE.BUSSINESS_ID,
    LE.BUSSINESS_CODE,
    LE.LEE_LOCALE,
    LE.LEE_VALUE
  FROM COMMON_GNOC.LANGUAGE_EXCHANGE LE
  JOIN
    (SELECT *
    FROM COMMON_GNOC.CAT_ITEM
    WHERE CATEGORY_ID = 263
    AND ITEM_CODE     = 'OPEN_PM'
    ) CAT1
  ON LE.APPLIED_SYSTEM = CAT1.ITEM_VALUE
  JOIN
    (SELECT *
    FROM COMMON_GNOC.CAT_ITEM
    WHERE CATEGORY_ID = 262
    AND ITEM_CODE     = 'OPEN_PM.IMPACT_SEGMENT'
    ) CAT2
  ON LE.APPLIED_BUSSINESS = CAT2.ITEM_VALUE
  WHERE LE.LEE_LOCALE     = :p_leeLocale
  ),
  list_result AS
  (SELECT ISM.IMPACT_SEGMENT_ID,
    ISM.IMPACT_SEGMENT_CODE,
    CASE
      WHEN llx.LEE_VALUE IS NULL
      THEN ISM.IMPACT_SEGMENT_NAME
      ELSE llx.LEE_VALUE
    END IMPACT_SEGMENT_NAME,
    ISM.APPLIED_SYSTEM,
    ISM.IS_ACTIVE
  FROM OPEN_PM.IMPACT_SEGMENT ISM
  LEFT JOIN list_language_exchange llx
  ON ISM.IMPACT_SEGMENT_ID = llx.BUSSINESS_ID
  )
SELECT IMPACT_SEGMENT_ID impactSegmentId,
  IMPACT_SEGMENT_CODE impactSegmentCode,
  IMPACT_SEGMENT_NAME impactSegmentName,
  APPLIED_SYSTEM appliedSystem
FROM list_result
WHERE IS_ACTIVE=1
