SELECT MR.SCHEDULE_ID scheduleId,
  MR.MARKET_CODE marketCode,
  CL.LOCATION_NAME marketName,
  CL.LOCATION_NAME nationName,
  MR.REGION region,
  MR.ARRAY_CODE arrayCode,
  MR.DEVICE_TYPE deviceType,
  MR.DEVICE_NAME deviceName,
  MR.DEVICE_CODE deviceCode,
  MR.DEVICE_ID deviceId,
  MR.IP_NODE ipNode,
  MR.VENDOR vendor,
  MR.BD_TYPE bdType,
  MR.STATION_CODE stationCode,
  DEV.NODE_AFFECTED nodeAffected,
  dev.OBJECT_ID objectId,
  MR.GROUP_CODE groupCode,
  TO_CHAR(MR.NEXT_DATE,'dd/MM/yyyy') nextDate,
  TO_CHAR(MR.LAST_DATE,'dd/MM/yyyy') lastDate,
  MR.MR_ID mrId,
  MR.CR_ID crId,
  WL.WLG_TEXT wlgText,
  SOF.DESCRIPTION_CR descriptionCr,
  unit.IMPLEMENT_UNIT implementUnitId,
  u1.UNIT_NAME implementUnitName,
  unit.CHECKING_UNIT checkingUnitId,
  u2.UNIT_NAME checkingUnitName,
  SOF.CYCLE cycle,
  SOF.CYCLE_TYPE cycleType,
  MR.NOTE,
  dev.UD ud,
  dev.DB db,
  DEV.BO_UNIT boUnit,
  dev.APPROVE_STATUS approveStatus,
  sof.PROCEDURE_NAME procedureName,
  TO_CHAR(MR.NEXT_DATE_MODIFY,'dd/MM/yyyy') nextDateModify,
  dev.LEVEL_IMPORTANT levelImportant,
  mr.IP_SERVER ip,
  dev.MR_CONFIRM_SOFT mrConfirm
FROM OPEN_PM.MR_SCHEDULE_IT mr
LEFT JOIN COMMON_GNOC.CAT_LOCATION cl
ON CL.LOCATION_ID = mr.MARKET_CODE
LEFT JOIN OPEN_PM.MR_CFG_CR_IMPL_UNIT unit
ON mr.MARKET_CODE     = unit.MARKET_CODE
AND MR.DEVICE_TYPE = UNIT.DEVICE_TYPE_ID
AND MR.REGION      = unit.REGION
LEFT JOIN COMMON_GNOC.UNIT u1
ON unit.IMPLEMENT_UNIT = u1.UNIT_ID
LEFT JOIN COMMON_GNOC.UNIT u2
ON unit.CHECKING_UNIT = u2.UNIT_ID
LEFT JOIN OPEN_PM.MR_CFG_PROCEDURE_IT_SOFT sof
ON MR.PROCEDURE_ID = SOF.PROCEDURE_ID
LEFT JOIN OPEN_PM.MR_SYN_IT_DEVICES dev
ON MR.MARKET_CODE  = dev.MARKET_CODE
AND MR.DEVICE_TYPE = dev.DEVICE_TYPE
AND MR.DEVICE_ID   = dev.OBJECT_ID
LEFT JOIN
  (SELECT RTRIM(XMLAGG(XMLELEMENT(E,WLG_TEXT,',').EXTRACT('//text()')
  ORDER BY WLG_TEXT).GetClobVal(),',') AS WLG_TEXT,
    WLG_OBJECT_ID
  FROM OPEN_PM.WORK_LOG
  WHERE WLG_OBJECT_TYPE = 2
  GROUP BY WLG_OBJECT_ID
  ) wl
ON MR.CR_ID      = WL.WLG_OBJECT_ID
WHERE 1          =1
AND SCHEDULE_ID IN (:scheduleIds)
