WITH list_language_exchange AS
  (SELECT LE.LEE_ID,
    LE.APPLIED_SYSTEM,
    LE.APPLIED_BUSSINESS,
    LE.BUSSINESS_ID,
    LE.BUSSINESS_CODE,
    LE.LEE_LOCALE,
    LE.LEE_VALUE
  FROM COMMON_GNOC.LANGUAGE_EXCHANGE LE
  JOIN
    (SELECT *
    FROM COMMON_GNOC.CAT_ITEM
    WHERE CATEGORY_ID = 263
    AND ITEM_CODE     = 'COMMON_GNOC'
    ) CAT1
  ON LE.APPLIED_SYSTEM = CAT1.ITEM_VALUE
  JOIN
    (SELECT *
    FROM COMMON_GNOC.CAT_ITEM
    WHERE CATEGORY_ID = 262
    AND ITEM_CODE     = 'COMMON_GNOC.CFG_CHILD_ARRAY'
    ) CAT2
  ON LE.APPLIED_BUSSINESS = CAT2.ITEM_VALUE
  WHERE LE.LEE_LOCALE     = :p_leeLocale
  ),
  list_language_exchange2 AS
  (SELECT LE.LEE_ID,
    LE.APPLIED_SYSTEM,
    LE.APPLIED_BUSSINESS,
    LE.BUSSINESS_ID,
    LE.BUSSINESS_CODE,
    LE.LEE_LOCALE,
    LE.LEE_VALUE
  FROM COMMON_GNOC.LANGUAGE_EXCHANGE LE
  JOIN
    (SELECT *
    FROM COMMON_GNOC.CAT_ITEM
    WHERE CATEGORY_ID = 263
    AND ITEM_CODE     = 'OPEN_PM'
    ) CAT1
  ON LE.APPLIED_SYSTEM = CAT1.ITEM_VALUE
  JOIN
    (SELECT *
    FROM COMMON_GNOC.CAT_ITEM
    WHERE CATEGORY_ID = 262
    AND ITEM_CODE     = 'OPEN_PM.IMPACT_SEGMENT'
    ) CAT2
  ON LE.APPLIED_BUSSINESS = CAT2.ITEM_VALUE
  WHERE LE.LEE_LOCALE     = :p_leeLocale
  ),
  list_result AS
  (SELECT c.CHILDREN_ID ,
    c.CHILDREN_CODE ,
    CASE
      WHEN llx.LEE_VALUE IS NULL
      THEN TO_CHAR(c.CHILDREN_NAME)
      ELSE TO_CHAR(llx.LEE_VALUE)
    END CHILDREN_NAME ,
    c.STATUS ,
    c.UPDATED_TIME ,
    c.UPDATED_USER ,
    c.PARENT_ID ,
    i.IMPACT_SEGMENT_CODE ,
    CASE
      WHEN llx2.LEE_VALUE IS NULL
      THEN i.IMPACT_SEGMENT_NAME
      ELSE llx2.LEE_VALUE
    END IMPACT_SEGMENT_NAME
  FROM COMMON_GNOC.CFG_CHILD_ARRAY c
  LEFT JOIN OPEN_PM.IMPACT_SEGMENT i
  ON c.PARENT_ID = i.IMPACT_SEGMENT_ID
  LEFT JOIN list_language_exchange llx
  ON c.CHILDREN_ID = llx.BUSSINESS_ID
  LEFT JOIN list_language_exchange2 llx2
  ON c.PARENT_ID = llx2.BUSSINESS_ID
  )
SELECT cr.CHILDREN_ID childrenId,
  cr.CHILDREN_CODE childrenCode,
  cr.CHILDREN_NAME childrenName,
  cr.STATUS status,
  cr.UPDATED_TIME updatedTime,
  cr.UPDATED_USER updatedUser,
  cr.PARENT_ID parentId,
  cr.IMPACT_SEGMENT_CODE parentCode,
  cr.IMPACT_SEGMENT_NAME parentName
FROM list_result cr
WHERE 1=1
