SELECT
i.ITEM_ID itemId,
i.ITEM_CODE itemCode,
i.ITEM_NAME itemName,
i.ITEM_VALUE itemValue,
i.CATEGORY_ID categoryId,
c.CATEGORY_NAME categoryIdName,
c.CATEGORY_CODE categoryCode,
c.DESCRIPTION description,
i.PARENT_ITEM_ID parentItemId,
i.STATUS status
FROM
COMMON_GNOC.CAT_ITEM i, COMMON_GNOC.CATEGORY c
WHERE
i.CATEGORY_ID = c.CATEGORY_ID
AND i.PARENT_ITEM_ID IS NULL AND STATUS = 1 AND c.CATEGORY_CODE = 'GNOC_YEAR' ORDER BY i.ITEM_NAME ASC
