WITH lst_lang AS
  (SELECT
    CASE
      WHEN l.LEE_VALUE IS NULL
      THEN c.ITEM_NAME
      ELSE l.LEE_VALUE
    END LEE_VALUE,
    c.ITEM_CODE ITEM_CODE
  FROM COMMON_GNOC.CAT_ITEM c
  LEFT JOIN COMMON_GNOC.LANGUAGE_EXCHANGE l
  ON c.ITEM_ID         = l.BUSSINESS_ID
  AND APPLIED_BUSSINESS=3
  AND l.APPLIED_SYSTEM =1
  AND l.LEE_LOCALE     =:lee_Locale
  WHERE c.STATUS       = 1
  AND c.CATEGORY_ID    =
    (SELECT CATEGORY_ID
    FROM COMMON_GNOC.CATEGORY
    WHERE CATEGORY_CODE='MR_SUBCATEGORY'
    AND STATUS         = 1
    )
  ORDER BY position,
    NLSSORT(ITEM_NAME,'NLS_SORT=vietnamese' )
  )
SELECT T1.SCHEDULE_ID scheduleId,
  T1.MARKET_CODE marketCode ,
  cl.location_name nationName,
  T1.ARRAY_CODE arrayCode,
  CASE
    WHEN ll.LEE_VALUE IS NULL
    THEN T1.ARRAY_CODE
    ELSE TO_CHAR(ll.LEE_VALUE)
  END arrayCodeStr,
  T1.DEVICE_TYPE deviceType ,
  T1.DEVICE_ID deviceId,
  T1.DEVICE_CODE deviceCode,
  T1.DEVICE_NAME deviceName ,
  T1.PROCEDURE_ID procedureId,
  T1.LAST_DATE lastDate ,
  T1.NEXT_DATE nextDate,
  T1.NEXT_DATE_MODIFY nextDateModify ,
  T1.MODIFY_USER modifyUser,
  T1.MODIFY_DATE modifyDate ,
  T1.UPDATED_DATE updatedDate,
  T1.GROUP_CODE groupCode,
  T1.MR_SOFT mrSoft,
  T1.MR_HARD mrHard ,
  T1.MR_12M mr12m,
  T1.STATION station,
  T1.REGION region,
  T1.MR_ID mrId,
  T13.MR_CODE mrCode,
  T1.MR_CONFIRM mrConfirm ,
  T11.CONFIG_NAME mrConfirmName,
  T1.MR_COMMENT mrComment,
  T1.NETWORK_TYPE networktype ,
  T2.MARKET_NAME marketName,
  T3.ARRAY_NAME arrayName,
  T4.PROCEDURE_NAME procedureName ,
  (
  CASE
    WHEN T1.MR_HARD = '1'
    THEN T1.MR_HARD_CYCLE
    ELSE T4.CYCLE
  END) cycle,
  T4.CYCLE_TYPE cycleType,
  (
  CASE
    WHEN T4.CYCLE_TYPE = 'M'
    THEN :cycleTypeM
    ELSE :cycleTypeD
  END) cycleTypeName ,
  T1.DEVICE_TYPE deviceTypeName,
  T9.IMPLEMENT_UNIT implementUnitId,
  T5.NODE_IP nodeIp,
  T5.USER_MR_HARD userMrHard ,
  T1.CR_ID crId ,
  T8.WO_ID woCode,
  T9.CHECKING_UNIT checkingUnitId,
  T5.VENDOR vendor,
  T5.IMPACT_NODE impactNode,
  T4.WO_CONTENT woContent ,
  T4.DESCRIPTION_CR crContent ,
  T10.CD_ID_HARD coordinatingUnitHard,
  T1.WO_ID woId,
  TO_CHAR(T1.LAST_DATE,'dd/MM/YYYY') lastDateStr,
  TO_CHAR(T1.NEXT_DATE,'dd/MM/YYYY') nextDateStr,
  TO_CHAR(T1.NEXT_DATE_MODIFY,'dd/MM/YYYY') nextDateModifyStr,
  TO_CHAR(T1.UPDATED_DATE,'dd/MM/YYYY') updatedDateStr
FROM OPEN_PM.MR_SCHEDULE_TEL T1
LEFT JOIN common_gnoc.cat_location cl
ON cl.location_id = T1.MARKET_CODE
LEFT JOIN OPEN_PM.MR_CAT_MARKET T2
ON T1.MARKET_CODE = T2.MARKET_CODE
LEFT JOIN OPEN_PM.MR_CAT_ARRAY T3
ON T1.ARRAY_CODE = T3.ARRAY_CODE
LEFT JOIN OPEN_PM.MR_CFG_PROCEDURE_TEL T4
ON T1.PROCEDURE_ID = T4.PROCEDURE_ID
LEFT JOIN OPEN_PM.MR_DEVICE T5
ON T1.DEVICE_ID    = T5.DEVICE_ID
AND T1.DEVICE_CODE = T5.NODE_CODE
LEFT JOIN
  (SELECT DISTINCT mr_id, wo_id FROM OPEN_PM.MR_NODES WHERE wo_id > 0
  ) T8
ON T1.MR_ID = T8.MR_ID
LEFT JOIN OPEN_PM.MR_CFG_CR_UNIT_TEL T9
ON T1.MARKET_CODE   = T9.MARKET_CODE
AND T1.DEVICE_TYPE  = T9.DEVICE_TYPE
AND T1.REGION       = T9.REGION
AND T1.ARRAY_CODE   = T9.ARRAY_CODE
AND T1.NETWORK_TYPE = T9.NETWORK_TYPE
LEFT JOIN OPEN_PM.MR_HARD_GROUP_CONFIG T10
ON T1.MARKET_CODE   = T10.MARKET_CODE
AND T1.DEVICE_TYPE  = T10.DEVICE_TYPE
AND T1.REGION       = T10.REGION
AND T1.ARRAY_CODE   = T10.ARRAY_CODE
AND T1.NETWORK_TYPE = T10.NETWORK_TYPE
AND T5.REGION_HARD  = T10.REGION
AND T5.STATION_CODE = T10.STATION_CODE
LEFT JOIN OPEN_PM.MR_CONFIG T11
ON T1.MR_CONFIRM   = T11.CONFIG_CODE
AND T11.CONFIG_GROUP='LY_DO_KO_BD'
LEFT JOIN lst_lang ll
ON ll.ITEM_CODE   = T1.ARRAY_CODE

LEFT JOIN MR T13
ON T13.MR_ID   = T1.MR_ID
WHERE 1           = 1
