SELECT T1.HARD_CD_ID hardCDId,
  T1.COUNTRY countryCode,
  T1.CD_ID cdId ,
  T1.STATION_CODE stationCode ,
  T1.CREATE_USER createUser ,
  T1.REGION region ,
  T2.LOCATION_NAME regionName,
  cl.location_name countryName,
  cd.WO_GROUP_NAME woGroupName
FROM OPEN_PM.MR_HARD_CD T1
LEFT JOIN COMMON_GNOC.CAT_LOCATION T2
ON T1.REGION   = T2.LOCATION_ID
AND T1.COUNTRY = TO_CHAR(T2.PARENT_ID)
LEFT JOIN COMMON_GNOC.CAT_LOCATION cl ON (T1.COUNTRY = cl.LOCATION_ID and cl.PARENT_ID is null and cl.status = 1)
LEFT JOIN WFM.WO_CD_GROUP cd ON (T1.CD_ID = cd.WO_GROUP_ID and cd.IS_ENABLE =1)
WHERE 1        = 1
