 select  
        cr.CR_ID crId,  
        cr.TITLE,  
        cr.CR_NUMBER crNumber,  
        cr.DESCRIPTION description,  
        cr.NOTES notes,  
        cr.CR_TYPE crType,  
        cr.PRIORITY priority,  
        cr.RISK risk,   
        cr.STATE state,  
        cr.cr_type_cat crTypeCat, 
        cr.PROCESS_TYPE_ID processTypeId,  
        cr.COUNTRY country,  
        cr.REGION region,  
        cr.CIRCLE circle,  
        cr.manage_unit_id manageUnitId,  
        cr.manage_user_id manageUserId,  
        cr.cr_number crNumber,  
        cr.SERVICE_AFFECTING serviceAffecting,  
        cr.AFFECTED_SERVICE affectedService,  
        cr.CHANGE_ORGINATOR changeOrginator,  
        cr.CHANGE_ORGINATOR_UNIT changeOrginatorUnit,  
        cr.CHANGE_RESPONSIBLE changeResponsible,  
        cr.CHANGE_RESPONSIBLE_UNIT changeResponsibleUnit,  
        cr.DUTY_TYPE dutyType,  
        cr.is_primary_cr isPrimaryCr,   
        cr.relate_to_primary_cr relateToPrimaryCr,   
        cr.relate_to_pre_approved_cr relateToPreApprovedCr,   
        cr.EARLIEST_START_TIME earliestStartTime,
        cr.LATEST_START_TIME latestStartTime,
        cr.DISTURBANCE_START_TIME disturbanceStartTime,
        cr.DISTURBANCE_END_TIME disturbanceEndTime,
        cr.IMPACT_AFFECT impactAffect,  
        cr.IMPACT_SEGMENT impactSegment,  
        cr.DEVICE_TYPE deviceType,  
        cr.CREATED_DATE createdDate,
        cr.UPDATE_TIME updateTime,
        cr.SUBCATEGORY subcategory  
        from open_pm.cr cr  
        where cr.cr_id = :cr_id
        AND cr.earliest_start_time >= trunc(sysdate) - 30 
